#pragma once
// ====================================
// Pin assignements of Pololu 3pi+ 2040 
// ====================================
// Do NOT EDIT THIS FILE!
// ====================================

// === Encoder-Pins ===
#define ENC_L_A 12  // Encoder Left
#define ENC_L_B 13
#define ENC_R_A 8   // Encoder Right
#define ENC_R_B 9

// === User Buttons ===
#define BTN_A 25  // Button A
#define BTN_B 1   // Button B (= QSPI SS)
#define BTN_C 0   // Button C (= OLED D/C)

// === OLED SPI ===
#define OLED_DC   0
#define OLED_RST  1
#define OLED_SCK  2
#define OLED_MOSI 3

// === Motor Drivers ===
#define LEFT_DIR   11
#define LEFT_PWM   15
#define RIGHT_DIR  10
#define RIGHT_PWM  14